### ISSUE TITLE
CultureNotFoundException

### ISSUE THREAD

**Issue by 15ah35** [ds160/remarkable-remember#5]
Application not opening in windows:

`System.Globalization.CultureNotFoundException
 HResult=0x80070057
 Message=Culture is not supported. (Parameter 'name')
az_az is an invalid culture identifier.
 Source=System.Private.CoreLib
 StackTrace:
  at System.Globalization.CultureInfo.GetCultureInfo(String name)
  at ReMarkableRemember.ViewModels.MyScriptLanguageViewModel..ctor(String code) in C:\Users\Lenovo\Downloads\remarkable-remember-main\remarkable-remember-main\src\ViewModels\MyScriptLanguageViewModel.cs:line 14
  at ReMarkableRemember.ViewModels.MyScriptLanguageViewModel.<>c.<GetLanguages>b__7_0(String code) in C:\Users\Lenovo\Downloads\remarkable-remember-main\remarkable-remember-main\src\ViewModels\MyScriptLanguageViewModel.cs:line 24
  at System.Linq.Enumerable.SelectListIterator`2.ToArray()
  at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
  at System.Linq.OrderedEnumerable`1.ToArray()
  at ReMarkableRemember.ViewModels.MyScriptLanguageViewModel.GetLanguages() in C:\Users\Lenovo\Downloads\remarkable-remember-main\remarkable-remember-main\src\ViewModels\MyScriptLanguageViewModel.cs:line 23
  at ReMarkableRemember.ViewModels.MainWindowModel..ctor(String dataSource) in C:\Users\Lenovo\Downloads\remarkable-remember-main\remarkable-remember-main\src\ViewModels\MainWindowModel.cs:line 34
  at ReMarkableRemember.App.OnFrameworkInitializationCompleted() in C:\Users\Lenovo\Downloads\remarkable-remember-main\remarkable-remember-main\src\App.axaml.cs:line 24
  at Avalonia.AppBuilder.SetupUnsafe()
  at Avalonia.AppBuilder.Setup()
  at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime)
  at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
  at ReMarkableRemember.Program.Main(String[] args) in 
C:\Users\Lenovo\Downloads\remarkable-remember-main\remarkable-remember-main\src\Program.cs:line 13`

Issue with az_Az and bs_ba. Changed code to az-Latn-AZ and bs-Latn-BA to get it to work.

**Comment by ds160** [comment]
I have modified the code. Could you test on Windows, please?
