### ISSUE TITLE
Receive core dump after during fetching items

### ISSUE THREAD

**Issue by torwag** [ds160/remarkable-remember#7]
Hi,
connected my rm1 via USB and getting an initial connect, it tries to fetch the item list and I get the following core dumped:
```
Unhandled exception. System.ArgumentOutOfRangeException: Value to add was out of range. (Parameter 'value')
   at System.DateTime.ThrowAddOutOfRange()
   at System.DateTime.AddMilliseconds(Double value)
   at ReMarkableRemember.Models.Tablet.Item..ctor(String id, String lastModified, String parent, String type, String visibleName) in /home/runner/work/remarkable-remember/remarkable-remember/src/Models/Tablet.cs:line 561
   at ReMarkableRemember.Models.Tablet.GetItems() in /home/runner/work/remarkable-remember/remarkable-remember/src/Models/Tablet.cs:line 172
   at ReMarkableRemember.Models.Controller.GetItems(Boolean includeTrashed) in /home/runner/work/remarkable-remember/remarkable-remember/src/Models/Controller.cs:line 51
   at ReMarkableRemember.ViewModels.MainWindowModel.UpdateItems() in /home/runner/work/remarkable-remember/remarkable-remember/src/ViewModels/MainWindowModel.cs:line 365
   at ReMarkableRemember.ViewModels.MainWindowModel.Update() in /home/runner/work/remarkable-remember/remarkable-remember/src/ViewModels/MainWindowModel.cs:line 349
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.X11.X11PlatformThreading.CheckSignaled()
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at ReMarkableRemember.Program.Main(String[] args) in /home/runner/work/remarkable-remember/remarkable-remember/src/Program.cs:line 13

Aborted (core dumped)
```
Restarting results in the same behaviour.

**Comment by ds160** [comment]
Hi,
I have never tested the software with a rm1. So maybe there are some problems like this.

Is it possible for you to send me an example of a `metadata` file from your tablet. With this a can parse the file properly without an exception.

Thank you for your support!

**Comment by ds160** [comment]
The software supports currently only rM2.
